language: node_js
node_js:
  - '10'
sudo: required
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm set progress=false
  - yarn install
script:
  - yarn ng lint
  # - yarn test
  - yarn e2e
  - yarn build
